### ISSUE TITLE
Can I run the code on Ubuntu14.04

### ISSUE THREAD

**Issue by Exception4U** [ras-sight/hratc2017_framework#7]
Hi I have system as lenovo p50 which is hybrid graphics .So it become tricky to install nvidia driver support on it on ubuntu 12.04 .Is there any we we can run our code of hratc on ubuntu 14.04

**Comment by ras-sight** [comment]
Unfortunately, our robot uses ROS Hydro, which is supported in Ubuntu 12.04, 12.10 and 13.04. So, if you want to run HRATC on Ubuntu 14.04, the solution is trying to compile ROS Hydro from source (unsupported installation - http://wiki.ros.org/hydro/Installation/Trusty).
